version: '3.1'

services:
  app:
    build:
    restart: always
    depends_on:
      - postgres
    ports:
      - "5005:5005"
    environment:
      - SQLALCHEMY_DATABASE_URI=${DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}